### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by cw789** [elixir-cldr/cldr_html#17]
Sorry to bother - I can't find the solution myself.
Starting with Elixir v1.15 I get always one of the following compilation errors:

(Edit: also now with Elixir v1.14.5)

```
==> cldr_html
Compiling 5 files (.ex)

== Compilation error in file lib/cldr_html_territories.ex ==
** (UndefinedFunctionError) function Cldr.Code.ensure_compiled?/1 is undefined (module Cldr.Code is not available)
    Cldr.Code.ensure_compiled?(Cldr.Territory)
    lib/cldr_html_territories.ex:1: (file)
    (elixir 1.15.4) lib/kernel/parallel_compiler.ex:377: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

```
==> cldr_html
Compiling 5 files (.ex)

== Compilation error in file lib/cldr_html_locale.ex ==
** (UndefinedFunctionError) function Cldr.Code.ensure_compiled?/1 is undefined (module Cldr.Code is not available)
    Cldr.Code.ensure_compiled?(Cldr.LocaleDisplay)
    lib/cldr_html_locale.ex:1: (file)
    (elixir 1.15.4) lib/kernel/parallel_compiler.ex:377: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

```
==> cldr_html
Compiling 5 files (.ex)

== Compilation error in file lib/cldr_html_units.ex ==
** (UndefinedFunctionError) function Cldr.Code.ensure_compiled?/1 is undefined (module Cldr.Code is not available)
    Cldr.Code.ensure_compiled?(Cldr.Unit)
    lib/cldr_html_units.ex:1: (file)
    (elixir 1.15.4) lib/kernel/parallel_compiler.ex:377: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

```
==> cldr_html
Compiling 5 files (.ex)

== Compilation error in file lib/cldr_html_currencies.ex ==
** (UndefinedFunctionError) function Cldr.Code.ensure_compiled?/1 is undefined (module Cldr.Code is not available)
    Cldr.Code.ensure_compiled?(Cldr.Currency)
    lib/cldr_html_currencies.ex:1: (file)
    (elixir 1.15.4) lib/kernel/parallel_compiler.ex:377: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

---

My deps:

```
{:ex_cldr, "~> 2.36"},
{:ex_cldr_territories, "~> 2.6"},
{:cldr_html, "~> 1.4"},
```

My Cldr configuration: 

```
use Cldr,
  locales: ["en", "de"],
  providers: [Cldr.Territory]
```

Am I doing something wrong? Or is cldr_html not compatible with the new parallel compiler stuff yet?

**Comment by kipcole9** [comment]
Of course that was the one combination I didn't try!  Thanks for the info, I'll work on this now.

**Comment by kipcole9** [comment]
I'm still struggling to reproduce even using your Elixir and OTP versions.  Next step is to create a standalone app and see if that has any differences.
```elixir
kip@Kips-MacBook-Pro cldr_html % asdf local elixir 1.15.4-otp-25
kip@Kips-MacBook-Pro cldr_html % asdf local erlang 26.0.2
kip@Kips-MacBook-Pro cldr_html % rm -rf _build
kip@Kips-MacBook-Pro cldr_html % iex -S mix
Mix requires the Hex package manager to fetch dependencies
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn]
* creating /Users/kip/.asdf/installs/elixir/1.15.4-otp-25/.mix/archives/hex-2.0.6
...
==> ex_cldr
Compiling 2 files (.erl)
Compiling 42 files (.ex)
Generated ex_cldr app
==> ex_cldr_currencies
Compiling 11 files (.ex)
Generated ex_cldr_currencies app
==> ex_cldr_numbers
Compiling 4 files (.erl)
Compiling 26 files (.ex)
Generated ex_cldr_numbers app
==> ex_money
Compiling 26 files (.ex)
Generated ex_money app
==> ex_cldr_lists
Compiling 3 files (.ex)
Generated ex_cldr_lists app
==> ex_cldr_units
Compiling 23 files (.ex)
Generated ex_cldr_units app
==> ex_cldr_territories
Compiling 3 files (.ex)
Generated ex_cldr_territories app
==> ex_cldr_locale_display
Compiling 7 files (.ex)
Generated ex_cldr_locale_display app
==> elixir_make
Compiling 6 files (.ex)
Generated elixir_make app
==> ex_cldr_collation
make: Nothing to be done for `all'.
Compiling 3 files (.ex)
Generated ex_cldr_collation app
==> cldr_html
Compiling 6 files (.ex)
Generating MyApp.Cldr for 8 locales named [:ar, :en, :he, :th, :und, ...] with a default locale named :en
Generated cldr_html app
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Interactive Elixir (1.15.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>

kip@Kips-MacBook-Pro cldr_html % asdf local erlang 25.3.2.5
kip@Kips-MacBook-Pro cldr_html % rm -rf _build
kip@Kips-MacBook-Pro cldr_html % iex -S mix
Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
...
==> ex_cldr
Compiling 2 files (.erl)
Compiling 42 files (.ex)
Generated ex_cldr app
==> ex_cldr_currencies
Compiling 11 files (.ex)
Generated ex_cldr_currencies app
==> ex_cldr_numbers
Compiling 4 files (.erl)
Compiling 26 files (.ex)
Generated ex_cldr_numbers app
==> ex_money
Compiling 26 files (.ex)
Generated ex_money app
==> ex_cldr_lists
Compiling 3 files (.ex)
Generated ex_cldr_lists app
==> ex_cldr_units
Compiling 23 files (.ex)
Generated ex_cldr_units app
==> ex_cldr_territories
Compiling 3 files (.ex)
Generated ex_cldr_territories app
==> ex_cldr_locale_display
Compiling 7 files (.ex)
Generated ex_cldr_locale_display app
==> elixir_make
Compiling 6 files (.ex)
Generated elixir_make app
==> ex_cldr_collation
make: Nothing to be done for `all'.
Compiling 3 files (.ex)
Generated ex_cldr_collation app
==> cldr_html
Compiling 6 files (.ex)
Generating MyApp.Cldr for 8 locales named [:ar, :en, :he, :th, :und, ...] with a default locale named :en
Generated cldr_html app
Interactive Elixir (1.15.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

**Comment by kipcole9** [comment]
OK, I can reproduce now. It's very weird - basically Elixir compiler is seeing `Cldr.Code` as a module, but then not trying to resolve and compile it. I'll keep digging, sorry for the inconvenience.

**Comment by kipcole9** [comment]
I have published [cldr_html version 1.5.1](https://hex.pm/packages/cldr_html/1.5.1) that resolves this issue (based upon my testing). The underlying issue - related to a change in the compilation order of dependencies - remains unresolved but this update will work on all Elixir/OTP supported versions (or it's a bug).

The changelog entry:

### Bug Fixes

* Fixes compile time module checking on Elixir 1.15 and OTP 25 or later. Thanks to @cw789 for the report. Closes #17.

**Comment by kipcole9** [comment]
Sorry this took so long to resolve, well outside my target SLA of 4 hours for resolution.

**Comment by kipcole9** [comment]
I appreciate the kind words, it helps with motivation for sure.  

This is a tricky compilation order issue and I still don't really understand why it's occurring. But I believe I have a workaround which is to configure `ex_cldr_currencies` as a dependency (whether you use it or not - it's a small library so shouldn't impact your memory footprint).

Add to `deps`:
```elixir
def deps do
  [
    ...
    {:ex_cldr_currencies, "~> 2.15"}
  ]
end
```
May I ask you to give this a try and report back?  If that results in a working system then I'll add that dep as a non-optional dependency in `cldr_html`.

**Comment by kipcole9** [comment]
Finally! Sorry this was such a trial. Can't believe I missed such an obvious omission.
